language: go

go:
    - go1.6
    - tip

script:
  - GOOS=linux go build
  - GOOS=darwin go build
  - GOOS=freebsd go build
  - GOOS=windows go build
  - GOARCH=386 go build

  - go test -v ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
