language: go
os:
  - linux
  - osx
go:
  - "go1.9"
  - "go1.10"
go_import_path: github.com/kataras/rizla
install:
  - go get ./...
script:
  - go test -v -cover ./...
after_script:
  # examples
  - cd ./_examples
  - go get ./...
  - go test -v -cover ./...
  - cd ../

after_success:
  - bash <(curl -s https://codecov.io/bash)
